// Writes .env.local from the running local Supabase stack (`supabase status`).
// Skips if .env.local already exists, unless --force is passed, so hand-added
// values are never clobbered by `pnpm dev`.
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

const PATH = ".env.local";
const force = process.argv.includes("--force");

if (existsSync(PATH) && !force) {
  console.log(`${PATH} already exists (use --force to regenerate).`);
  process.exit(0);
}

const raw = execFileSync("./scripts/supabase.sh", ["status", "-o", "env"], {
  encoding: "utf8",
  stdio: ["ignore", "pipe", "ignore"],
});
const status = Object.fromEntries(
  raw
    .split("\n")
    .map((line) => line.match(/^([A-Z_]+)="?(.*?)"?$/))
    .filter((m): m is RegExpMatchArray => !!m)
    .map((m) => [m[1], m[2]]),
);

for (const key of ["API_URL", "PUBLISHABLE_KEY", "SECRET_KEY", "DB_URL"]) {
  if (!status[key]) {
    console.error(
      `\`supabase status\` did not report ${key} — is the stack running? (pnpm db:start)`,
    );
    process.exit(1);
  }
}

const signingKey = execFileSync("pnpm", ["-s", "keys:ensure", "--print"], { encoding: "utf8" });

const body = `# Generated by \`pnpm env:local\` from the local Supabase stack. Safe to regenerate.
# Local-only values: these are the Supabase CLI's shared development defaults.

# Used by the app in the browser and on the server, and by scripts
NEXT_PUBLIC_SUPABASE_URL=${status.API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${status.PUBLISHABLE_KEY}

# Used by the app on the server only, and by scripts. Secret: never expose to the
# browser (no NEXT_PUBLIC_ prefix). Regenerating BETTER_AUTH_SECRET signs everyone out.
BETTER_AUTH_URL=http://localhost:3200
BETTER_AUTH_SECRET=${randomBytes(32).toString("base64")}
# BetterAuth's tables (owner connection).
DATABASE_URL=${status.DB_URL}
# Signs each session's Supabase token (private key of supabase/signing_keys.json).
SUPABASE_JWT_SIGNING_KEY='${signingKey}'

# Used by scripts/ only (service role: bypasses RLS). Never import into src/.
SUPABASE_SECRET_KEY=${status.SECRET_KEY}

# Optional, add by hand: enables "Continue with Google" for athletes.
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
`;

writeFileSync(PATH, body);
console.log(`Wrote ${PATH} for ${status.API_URL}`);
