// Writes .env.local from the running local Supabase stack (`supabase status`).
// Skips if .env.local already exists, unless --force is passed, so hand-added
// values are never clobbered by `pnpm dev`.
import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";

const PATH = ".env.local";
const force = process.argv.includes("--force");

if (existsSync(PATH) && !force) {
  console.log(`${PATH} already exists (use --force to regenerate).`);
  process.exit(0);
}

const raw = execFileSync("./scripts/supabase.sh", ["status", "-o", "env"], {
  encoding: "utf8",
  stdio: ["ignore", "pipe", "ignore"],
});
const status = Object.fromEntries(
  raw
    .split("\n")
    .map((line) => line.match(/^([A-Z_]+)="?(.*?)"?$/))
    .filter((m): m is RegExpMatchArray => !!m)
    .map((m) => [m[1], m[2]]),
);

for (const key of ["API_URL", "ANON_KEY", "SECRET_KEY", "DB_URL"]) {
  if (!status[key]) {
    console.error(
      `\`supabase status\` did not report ${key} — is the stack running? (pnpm db:start)`,
    );
    process.exit(1);
  }
}

const body = `# Generated by \`pnpm env:local\` from the local Supabase stack. Safe to regenerate.
# Local-only values: these are the Supabase CLI's shared development defaults.

# Used by the app (browser + server)
NEXT_PUBLIC_SUPABASE_URL=${status.API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${status.ANON_KEY}

# Used by scripts/ only (service role: bypasses RLS). Never import into src/.
SUPABASE_SECRET_KEY=${status.SECRET_KEY}
DATABASE_URL=${status.DB_URL}
`;

writeFileSync(PATH, body);
console.log(`Wrote ${PATH} for ${status.API_URL}`);
